[package]
name = "gantt-chart-creator"
version = "0.1.0"
description = "Gantt Chart Creator desktop application"
authors = ["Hassaan Shah"]
edition = "2021"

[lib]
name = "gantt_chart_creator_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
